# Generated by Django 5.2.7 on 2026-09-23 18:15

import missculture.media_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_financesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='photo',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/contestants', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/events', verbose_name='featured_image'),
        ),
        migrations.AlterField(
            model_name='guestspeaker',
            name='photo',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/guest-speakers', verbose_name='photo'),
        ),
    ]

