# Generated by Django 5.2.7 on 2026-09-23 18:15

import gallery.models
import missculture.media_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_add_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerysettings',
            name='hero_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/gallery/settings', validators=[gallery.models.validate_cloudinary_image_size], verbose_name='hero_image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/gallery/photos', validators=[gallery.models.validate_cloudinary_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/gallery/thumbnails', validators=[gallery.models.validate_cloudinary_image_size], verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='photocollection',
            name='cover_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/gallery/collections', validators=[gallery.models.validate_cloudinary_image_size], verbose_name='cover_image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/gallery/video_thumbnails', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=missculture.media_fields.R2FileField(blank=True, max_length=500, null=True, resource_type='video', upload_to='r2/missculture/gallery/videos', verbose_name='video_file'),
        ),
    ]

