# Generated by Django 5.2.7 on 2026-09-23 18:15

import missculture.media_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_partner_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='hero_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/about', verbose_name='hero'),
        ),
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='leader_1_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/about/leaders', verbose_name='leader_1'),
        ),
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='leader_2_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/about/leaders', verbose_name='leader_2'),
        ),
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='leader_3_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/about/leaders', verbose_name='leader_3'),
        ),
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='leader_4_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/about/leaders', verbose_name='leader_4'),
        ),
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='leader_5_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/about/leaders', verbose_name='leader_5'),
        ),
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='leader_6_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/about/leaders', verbose_name='leader_6'),
        ),
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='mission_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/about', verbose_name='mission'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/achievements', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='profile_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/ambassador', verbose_name='profile_image'),
        ),
        migrations.AlterField(
            model_name='ambassadorpagesettings',
            name='hero_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/ambassador', verbose_name='hero'),
        ),
        migrations.AlterField(
            model_name='ambassadorpagesettings',
            name='profile_image',
            field=missculture.media_fields.R2ImageField(blank=True, help_text='Profile image for ambassador (also used on homepage spotlight)', max_length=500, null=True, upload_to='r2/missculture/pages/ambassador', verbose_name='profile'),
        ),
        migrations.AlterField(
            model_name='contactpagesettings',
            name='hero_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/contact', verbose_name='hero'),
        ),
        migrations.AlterField(
            model_name='contributepagesettings',
            name='hero_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/contribute', verbose_name='hero'),
        ),
        migrations.AlterField(
            model_name='culturalcommunity',
            name='image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/communities', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='culturalheritage',
            name='audio_clip',
            field=missculture.media_fields.R2FileField(blank=True, max_length=500, null=True, resource_type='video', upload_to='r2/missculture/audio', verbose_name='audio_clip'),
        ),
        migrations.AlterField(
            model_name='culturalheritage',
            name='image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/heritage', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='culturalheritage',
            name='video_clip',
            field=missculture.media_fields.R2FileField(blank=True, max_length=500, null=True, resource_type='video', upload_to='r2/missculture/heritage-video', verbose_name='video_clip'),
        ),
        migrations.AlterField(
            model_name='eventspagesettings',
            name='hero_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/events', verbose_name='hero'),
        ),
        migrations.AlterField(
            model_name='faqpagesettings',
            name='hero_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/faq', verbose_name='hero'),
        ),
        migrations.AlterField(
            model_name='gallerypagesettings',
            name='hero_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/gallery', verbose_name='hero'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='ambassador_highlight_image',
            field=missculture.media_fields.R2ImageField(blank=True, help_text='Image for Ambassador highlight card on homepage', max_length=500, null=True, upload_to='r2/missculture/pages/home/highlights', verbose_name='ambassador_highlight'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/home', verbose_name='hero'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='kenya_highlight_image',
            field=missculture.media_fields.R2ImageField(blank=True, help_text='Image for Kenya highlight card on homepage', max_length=500, null=True, upload_to='r2/missculture/pages/home/highlights', verbose_name='kenya_highlight'),
        ),
        migrations.AlterField(
            model_name='kenyagalleryphoto',
            name='image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/kenya-gallery', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='kenyapagesettings',
            name='hero_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/kenya', verbose_name='hero'),
        ),
        migrations.AlterField(
            model_name='kenyaregion',
            name='image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/regions', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/partners', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='partnershippagesettings',
            name='hero_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/partnership', verbose_name='hero'),
        ),
        migrations.AlterField(
            model_name='privacypagesettings',
            name='hero_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/privacy', verbose_name='hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_global',
            field=missculture.media_fields.R2ImageField(blank=True, help_text='Logo for Miss Culture Global (parent organization)', max_length=500, null=True, upload_to='r2/missculture/logos', verbose_name='logo_global'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_kenya',
            field=missculture.media_fields.R2ImageField(blank=True, help_text='Logo for Miss Culture Global Kenya (local franchise)', max_length=500, null=True, upload_to='r2/missculture/logos', verbose_name='logo_kenya'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mpesa_logo',
            field=missculture.media_fields.R2ImageField(blank=True, help_text='M-Pesa logo for payment sections', max_length=500, null=True, upload_to='r2/missculture/logos', verbose_name='mpesa_logo'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/team', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='termspagesettings',
            name='hero_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/terms', verbose_name='hero'),
        ),
        migrations.AlterField(
            model_name='votingpagesettings',
            name='event_1_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/voting/events', verbose_name='event_1'),
        ),
        migrations.AlterField(
            model_name='votingpagesettings',
            name='event_2_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/voting/events', verbose_name='event_2'),
        ),
        migrations.AlterField(
            model_name='votingpagesettings',
            name='event_3_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/voting/events', verbose_name='event_3'),
        ),
        migrations.AlterField(
            model_name='votingpagesettings',
            name='event_4_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/voting/events', verbose_name='event_4'),
        ),
        migrations.AlterField(
            model_name='votingpagesettings',
            name='hero_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/voting', verbose_name='hero'),
        ),
        migrations.AlterField(
            model_name='votingpagesettings',
            name='participant_1_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/voting/participants', verbose_name='participant_1'),
        ),
        migrations.AlterField(
            model_name='votingpagesettings',
            name='participant_2_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/voting/participants', verbose_name='participant_2'),
        ),
        migrations.AlterField(
            model_name='votingpagesettings',
            name='participant_3_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/voting/participants', verbose_name='participant_3'),
        ),
        migrations.AlterField(
            model_name='votingpagesettings',
            name='participant_4_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/voting/participants', verbose_name='participant_4'),
        ),
        migrations.AlterField(
            model_name='votingpagesettings',
            name='participant_5_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/voting/participants', verbose_name='participant_5'),
        ),
        migrations.AlterField(
            model_name='votingpagesettings',
            name='participant_6_image',
            field=missculture.media_fields.R2ImageField(blank=True, max_length=500, null=True, upload_to='r2/missculture/pages/voting/participants', verbose_name='participant_6'),
        ),
    ]

